<a href="https://colab.research.google.com/github/sumardikawaisnawa/data_analyticst/blob/main/UTSDataanalityc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [2]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = "/content/gdrive/My Drive/Kaggle"
# /content/gdrive/My Drive/Kaggle is the path where kaggle.json is present in the Google Drive

In [3]:
#changing the working directory
%cd /content/gdrive/My Drive/Kaggle
#Check the present working directory using pwd command

/content/gdrive/My Drive/Kaggle

In [20]:
!kaggle datasets download -d alrizacelk/moto-gp-world-championship19492022

Downloading moto-gp-world-championship19492022.zip to /content/gdrive/My Drive/Kaggle
  0% 0.00/33.9k [00:00<?, ?B/s]
100% 33.9k/33.9k [00:00<00:00, 6.45MB/s]

In [21]:
!ls

cash_flow.csv  map_ticker_to_company.csv
kaggle.json    moto-gp-world-championship19492022.zip

In [22]:
#unzipping the zip files and deleting the zip files
!unzip \*.zip  && rm *.zip

Archive:  moto-gp-world-championship19492022.zip
  inflating: constructure-world-championship.csv
  inflating: grand-prix-events-held.csv
  inflating: grand-prix-race-winners.csv
  inflating: riders-finishing-positions.csv
  inflating: riders-info.csv
  inflating: same-nation-podium-lockouts.csv

In [23]:
import pandas as pd

In [24]:
df = pd.read_csv(r'same-nation-podium-lockouts.csv')

In [25]:
df.head()

   Season                                  Track Riders` Nation    Class
0    2022                    Termas de Río Hondo             ES  MotoGP™
1    2021                  Circuit Ricardo Tormo             ES   Moto3™
2    2021  Misano World Circuit Marco Simoncelli             IT   MotoE™
3    2021  Misano World Circuit Marco Simoncelli             IT   Moto3™
4    2021                    Silverstone Circuit             IT   Moto3™

In [26]:
df = pd.read_csv(r'constructure-world-championship.csv')

In [27]:
df.head()

   Season Constructor    Class
0    2021      Yamaha  MotoGP™
1    2021       Kalex   Moto2™
2    2021         KTM   Moto3™
3    2021    Energica   MotoE™
4    2020      Suzuki  MotoGP™

In [29]:
df = pd.read_csv(r'grand-prix-events-held.csv')

In [30]:
df.head()

   Times                            Track Country
0    280                 TT Circuit Assen      NL
1    168                Automotodrom Brno      CZ
2    131                Spa-Francorchamps      BE
3    125                      Sachsenring      DE
4    118  Circuito de Jerez - Angel Nieto      ES

In [31]:
df = pd.read_csv(r'grand-prix-race-winners.csv')

In [32]:
df.head()

,Circuit,Class,Constructor,Country,Rider,Season
0,Circuit Of The Americas,Moto3™,KTM,ES,Jaume Masia,2022
1,Circuit Of The Americas,Moto2™,Kalex,IT,Tony Arbolino,2022
2,Circuit Of The Americas,MotoGP™,Ducati,IT,Enea Bastianini,2022
3,Termas de Río Hondo,Moto3™,GASGAS,ES,Sergio Garcia,2022
4,Termas de Río Hondo,MotoGP™,Aprilia,ES,Aleix Espargaro,2022

In [34]:
df = pd.read_csv(r'riders-finishing-positions.csv')

In [35]:
df.head()

,Rider,Victories,NumberofSecond,NumberofThird,Numberof4th,Numberof5th,Numberof6th,Country
0,Giacomo Agostini,122,67,53,48,34,24,IT
1,Valentino Rossi,115,52,47,38,30,21,IT
2,Angel Nieto,90,51,40,35,25,21,ES
3,Marc Marquez,85,44,36,28,23,21,ES
4,Mike Hailwood,76,41,33,26,22,20,GB

In [36]:
df = pd.read_csv(r'riders-info.csv')

In [37]:
df.head()

,Riders All Time in All Classes,Victories,2nd places,3rd places,Pole positions from '74 to 2022,Race fastest lap to 2022,World Championships
0,AGOSTINI Giacomo,122,35.0,2.0,9.0,117.0,15.0
1,ROSSI Valentino,115,67.0,53.0,65.0,96.0,9.0
2,NIETO Angel,90,35.0,14.0,34.0,81.0,13.0
3,MARQUEZ Marc,85,36.0,17.0,90.0,75.0,8.0
4,HAILWOOD Mike,76,25.0,11.0,NaN,79.0,9.0